config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :users, only: [:new, :show, :create, :edit, :update]

  resources :meals do
    resources :foods, only: [:new, :index, :create]
  end

  resources :foods, only: [:new, :show, :edit, :update, :destroy, :index]

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get 'welcome'
    end
  end

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user, optional: true
  has_many :meal_compositions
  has_many :foods, through: :meal_compositions

  validates :time, presence: true

  scope :today, ->(user) { where("time >= :begin_day AND time <= :end_day AND user_id = :user_arg ", begin_day: DateTime.now.midnight, end_day: DateTime.now.midnight + 1, user_arg: user.id).order(time: :asc) }

  def self.calories_todays_meals(user)
    Meal.today(user).collect { |meal| MealComposition.total_calories_in_meal(meal) }.sum
  end

  def self.todays_macronutrient_total(user, macronutrient)
    Meal.today(user).collect { |meal| meal.grams_of_macronutrient(macronutrient) }.sum
  end

  def self.todays_macronutrient_calories(user, macronutrient)
    if macronutrient.category != "fat"
      Meal.todays_macronutrient_total(user, macronutrient) * 4
    else
      Meal.todays_macronutrient_total(user, macronutrient) * 9
    end
  end

  def self.todays_percent_calories_of_macro(user, macronutrient)
    (Meal.todays_macronutrient_calories(user, macronutrient).to_f / Meal.calories_todays_meals(user) * 100).round(2)
  end

  def calories
    MealComposition.total_calories_in_meal(self)
  end

  def calories_from_macronutrient(macronutrient)
    MealComposition.total_calorie_from_macro_in_meal(self, macronutrient)
  end

  def percent_calories_macronutrient(macronutrient)
    (calories_from_macronutrient(macronutrient).to_f / calories * 100).round(2)
  end

  def grams_of_macronutrient(macronutrient)
    MealComposition.total_grams_of_macro_in_meal(self, macronutrient)
  end

  def add_food=(add_food)
    self.meal_compositions.build(food_id: add_food[:food_id], food_servings: add_food[:servings])
  end

  def remove_food=(meal_composition)
    MealComposition.find(meal_composition).destroy
  end

  def food_attributes=(food_attributes)
    food_attributes.each do |food_attribute|
      if food_attribute[:food_id].present?
        food_attribute[:servings] = 1 unless food_attribute[:servings].present?
        self.meal_compositions.build(food_id: food_attribute[:food_id], food_servings: food_attribute[:servings])
      end
    end
  end

  def new_foods=(new_foods)
    new_foods.each do |new_food|
      new_food[:food_servings] = 1 unless new_food[:food_servings].present?
      if new_food[:food_name].present?
        find_or_create_food(food_name: new_food[:food_name], food_servings: new_food[:food_servings], attributes: new_food[:macronutrient_categories])
      end
    end
  end

  def find_or_create_food(food_name:, food_servings:, attributes:)
    if food = Food.find_by(name: food_name)
      self.meal_compositions.build(food_id: food.id, food_servings: food_servings)
    else
      food = Food.create(name: food_name)
      assign_food_composition(attributes: attributes, food: food)
      food.save
      self.meal_compositions.build(food_id: food.id, food_servings: food_servings)
    end
  end

  def assign_food_composition(attributes:, food:)
    attributes.each do |attribute|
      attribute[:grams] = 0 unless attribute[:grams].present?
      food.food_compositions.build(food_id: food.id, macronutrient_id: attribute[:macronutrient_id], macronutrient_grams: attribute[:grams]) if attribute[:macronutrient_id].present?
    end
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authorized?
  before_action :find_meal, only: [:show, :edit, :update, :destroy]
  before_action :find_macronutrients, only: [:new, :create, :show, :update]

  def index
    @meals = current_user.meals
    @all_meals = Meal.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @meals, status: 200 }
    end
  end

  def new
    @foods = Food.all
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.user = current_user

    if @meal.save
      respond_to do |format|
        format.html { redirect_to user_path(current_user) }
        format.json { render json: @meal, meta: { table_data: NewTableDataService.new.call_todays_meals(current_user) }, adapter: :json }
      end
    else
      @foods = Food.all
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @meal, status: 200 }
    end
  end

  def edit

  end

  def update
    @food = Food.find(params[:meal][:add_food][:food_id]) if params[:meal][:add_food]
    if @meal.update(meal_params)
      respond_to do |format|
        format.html { redirect_to meal_path(@meal) }
        format.json { render json: {
          food: @food || "",
          meal_composition: @meal.meal_compositions.last,
          table_data: NewTableDataService.new.call_meal(@meal)
           }
         }
       end
    else
      render :show
    end
  end

  def destroy
    @meal.meal_compositions.each do |meal_composition|
      meal_composition.destroy
    end
    @meal.destroy
    redirect_to user_path(current_user), notice: "You just deleted a meal for #{@meal.time.strftime('%A, %b %d, %l:%M %p')}."
  end

  private

  def meal_params
    params.require(:meal).permit(:servings, :remove_food, :time, food_attributes: [:food_id, :servings], new_foods: [:food_name, :food_servings, macronutrient_categories: [:macronutrient_id, :grams]], add_food: [:food_id, :servings])
  end

  def find_meal
    @meal = Meal.find(params[:id])
  end

  def find_macronutrients
    @macronutrients = Macronutrient.all
  end

end

app/helpers/meals_helper.rb
module MealsHelper

  def meal_errors_present?(meal)
    if meal.errors[:food_compositions].present? || meal.errors[:meal_compositions].present?
      content_tag :div, class: "field_with_errors" do
        yield
      end
    else
      div_tag_for_food_attributes do
        yield
      end
    end
  end

  def meal_time_link(meal, user)
    if user.nil?
      link_to meal_time(meal), meal_path(meal)
    else
      link_to meal_hour_min(meal), meal_path(meal), rel: "shortcut icon"
    end
  end

  def meal_time(meal)
    meal.time.strftime('%A, %b %d, @ %l:%M %p')
  end

  def meal_hour_min(meal)
    meal.time.strftime('%b %d, @ %l:%M %p')
  end

  def div_tag_for_food_attributes
    content_tag :div, class: "field" do
      yield
    end
  end

  def tr_class(index)
    if index.odd?
      content_tag :tr, class: "pure-table-odd" do
        yield
      end
    else
      content_tag :tr do
        yield
      end
    end
  end

end

app/views/meals/_form.html.erb
<%= form_for(meal) do |f| %>

  <%= f.datetime_select :time, prompt: {day: 'Choose day', month: 'month', year: 'year', hour: "hour", minute: "min"} %>

  <div id="add-food-form">
  <%= meal_errors_present?(meal) do%>
    <% 3.times do %>
      <%= select_tag 'meal[food_attributes][][food_id]', options_from_collection_for_select(foods, :id, :name), prompt: 'select food' %>
      <%= text_field_tag 'meal[food_attributes][][servings]', nil, placeholder: 'servings' %>
    <%= tag :br %>
    <% end %>
  <% end %>
  <div id="add-add-food-form"><div>
  <a href="#" id="add-food-form-link">Add another food</a>
  </div>

  <div id="create-new-food-form">
  <%= div_tag_for_food_attributes do %>
    <%= content_tag(:p, "And/Or Create Foods For Meal") %>

    <%= meal_errors_present?(meal) do%>
      <%= label_tag 'Food Name:' %>
      <%= text_field_tag 'meal[new_foods][][food_name]'%>
      <%= tag(:br) %>

      <% macronutrients.each do |macronutrient| %>
        <%= macronutrient.category%> <%= hidden_field_tag 'meal[new_foods][][macronutrient_categories][][macronutrient_id]', macronutrient.id %>
        <%= text_field_tag 'meal[new_foods][][macronutrient_categories][][grams]', nil, placeholder: 'grams' %>
        <%= tag(:br) %>
      <% end %>
      <%= text_field_tag 'meal[new_foods][][food_servings]', nil, placeholder: 'servings' %>
    <% end %>
    <div id="add-new-food-form">
  <% end %>

  <a href="#" id="create-new-food-form-link">Create another food</a>
  </div>
  <%= tag(:br) %>
  <%= f.submit %>
<% end %>

<script type="text/javascript" charset="utf-8">
  console.log('hello on new meal page');

  $(document).on('turbolinks:load', function(){
    $('#create-new-food-form-link').on('click', function(e) {
      e.preventDefault();
      console.log('In the new food form click');

      const newFoodForm = HandlebarsTemplates['new_meal_food'];
      $('#add-new-food-form').prepend(newFoodForm);
    })

    $('#add-food-form-link').on('click', function(e) {
      e.preventDefault();
      console.log('In the add food form click');
      $.get('/foods', function(data) {
        console.log(data)
        const foods = data;
        const addFoodForm = HandlebarsTemplates['add_meal_food']({
          foods: foods
        })
        $('#add-add-food-form').prepend(addFoodForm);
      })
    })
  });

</script>

app/views/meals/_macronutrients_table.html.erb
<% macronutrients.each.with_index(1) do |macronutrient, i| %>
  <%= tr_class(i) do %>
    <%= content_tag :td, macronutrient.category.upcase %>
    <%= content_tag :td, item.grams_of_macronutrient(macronutrient) %>
    <%= content_tag :td, item.percent_calories_macronutrient(macronutrient) %>
  <% end %>
<% end %>

app/views/meals/_meal_foods.html.erb
<% meal.meal_compositions.each do |meal_composition| %>

  <%= content_tag :li do %>
    <%= link_to meal_composition.food.name, food_path(meal_composition.food.id), class: "food-link" %>
    <%= tag :br %>
    <%= "Servings: #{meal_composition.food_servings}" %>
  <% end %>

  <%= content_tag :li do %>
    <%= button_to "remove", meal_path(meal), form_class: "remove-food", method: :patch, params: {:meal => {:remove_food => meal_composition.id}, data: {confirm: "Are you sure you want to remove #{meal_composition.food.name}?"}} %>
  <% end %>

<% end %>

app/views/meals/_meals_list.html.erb
<div id="todays-meal-list">
  <% meals.each do |meal| %>
    <%= content_tag :ul do %>
      <%= content_tag :li do %>
        <%= meal_time_link(meal, current_user) %>
      <% end %>
    <% end %>

    <%= content_tag :p, class: "calories-list" do %>
      - <%= meal.calories %> calories
        <small><%= link_to ' see meal creator', '#', class: "see-creator", data: meal.id %></small>
        <ul id="meal-creator-<%= meal.id %>"></ul>
    <% end %>

  <% end %>
</div>

app/views/meals/edit.html.erb
<h1> Update time of the meal </h1>

<%= form_for(@meal) do |f| %>
  <%= f.datetime_select :time %>
  <%= f.submit %>
<% end %>
<!--link to destroy meal-->
<%= button_to "Delete Meal", meal_path(@meal), method: :delete, form_class: "delete-meal", data: {confirm: "Are you sure you want to remove this meal?"} %>

app/views/meals/index.html.erb
<h1> All Meals </h1>

<h3> Meals </h3>
<%= render 'meals_list', meals: @all_meals %>

<script type="text/javascript" charset="utf-8">
  console.log('hello on meals index.');

  $(document).on('turbolinks:load', function() {
    console.log('in turbolinks load');

    $('.see-creator').on('click', function(e) {

      e.preventDefault();
      console.log('just clicked on this meal creator link', this);
      //get meal using AJAX
      //link should contain meals id in a data attribute
      //grab data id, and send with /meals to hit meal show route
      //return individual meal, and create a meal object, then use the meal object to display that meals user in <li></li> tags.

      const mealId =this.attributes.data.value;
      $(this).hide();

      $.get('/meals/' + mealId, function(data) {
        //want json back
        //use data to create a meal object with a username
        //use this meal object to display the user for the meal in <li></li> tags
        console.log('in ajax success function', data);
        const meal = new Meal(data.id, data.time, data.meal_compositions);
        if (data.user === null) {
          meal.user = "This meal does not have a user."
        } else {
          meal.user = data.user.username;
        }

        const userLi = '<ul><li>' + meal.user + '</li></ul>';

        $('#meal-creator-' + meal.id).append(userLi);

      }, "json");
    })
  })
</script>

app/views/meals/new.html.erb
<h1> Create New Meal </h1>

<%= errors_list(@meal) %>

<%= render 'form', meal: @meal, foods: @foods, macronutrients: @macronutrients %>

app/views/meals/show.html.erb
<%= content_tag :h1, "Meal for #{meal_time(@meal)}" %>

<%= errors_list(@meal) %>

  <div>
    <%= button_tag "See Foods", type: 'button', class: "see-foods", id: "see-foods", data: "#{@meal.id}" %>
  </div>

  <h3 id="title"></h3>
  <%= content_tag :ul, nil, class: "col-1", id: "foods" %>

<div class="col-2">
  <h5 id="meal_show_macro"> Macronutrient Tracker </h5>
  <table class="pure-table">
      <thead>
          <tr>
              <th>Category</th>
              <th>Grams</th>
              <th>Percentage of Calories</th>
          </tr>
      </thead>
      <tbody>
        <%= render 'macronutrients_table', macronutrients: @macronutrients, item: @meal %>
      </tbody>
  </table>
</div>

  <!-- dropdown menu to add existing foods to current meal -->
  <div id="form" class="col-2"></div>
  <%= form_tag(meal_path(@meal), method: :patch, id: "add-food-form", data: @meal.id) do %>
    <%= meal_errors_present?(@meal) do %>
      <%= select_tag 'meal[add_food][food_id]', options_from_collection_for_select(Food.all, :id, :name), prompt: "Select Food"  %>
      <%= text_field_tag 'meal[add_food][servings]', nil, placeholder: 'servings' %>
      <%= submit_tag "Add Food" %>
    <% end %>
  <% end %>

<h4 id="create-title" class="col-2"><h4>
  <%= content_tag :p, id: "add-form" do %>
    <%= link_to "Create Food", new_meal_food_path(@meal), id: "new-food-link", data: "#{@meal.id}" %>
  <% end %>

<!-- link to edit meals time -->
<div>
  <%= content_tag :div, class: "col-2" do %>
   <%= link_to "Update Meal Time", edit_meal_path(@meal) %>
  <% end %>
</div>

  <script type="text/javascript" charset="utf-8">
    console.log('hello on show');
    //This function adds a listener to the remove button in the foods list
    function removeFoodListener() {
      $('button#remove-food').on('click', function(e) {
        e.preventDefault();
        e.stopPropagation();
        console.log('In the remove food function', this);

        let mealCompositionId = this.attributes.data.value;
        let mealId = $('body').data('meal-foods').id
        //removing the parent li this button is under from the DOM.
        $(this).closest('ul').closest('li').remove();

        $.ajax({
          type: "PATCH",
          url: "/meals/" + mealId,
          data: { meal: { remove_food: mealCompositionId } },
          success: success,
          dataType: 'json'
        });

        function success(data) {
          console.log('We have data back from updating removing the food', data);
          //take the data and create a new table
          macronutrientTable = new MacronutrientTable(data.table_data.carbohydrate, data.table_data.percent_calories_of_carbohydrate,
          data.table_data.protein,data.table_data.percent_calories_of_protein, data.table_data.fat, data.table_data.percent_calories_of_fat)
          //update the table on the DOM
          macronutrientTable.updateTable();
        }
      })
    }
    function resetSubmit() {
      $('#add-food-form input[type="submit"]').prop('disabled', false);
    }

    $(document).on('turbolinks:load', function() {
      $('#see-foods').off();
      $('#new-food-link').off();
      $('#add-food-form').off("submit");

      console.log('turbolinks loads');
      //See Foods button listener
      $('#see-foods').on('click', function(e) {
        e.preventDefault();
        e.stopPropagation();
        $('#see-foods').off();
        console.log('You just clicked the button');
        //identifying which meal it is through the data attribute on the button which contains the meal id.
        const mealId = this.attributes.data.value;
        $.getJSON('/meals/' + mealId, function(data) {
          console.log('in the get response');
          //create a meal object with the json response
          let meal = new Meal(data.id, data.time, data.meal_compositions);
          $("body").data( "meal-foods", meal);
          $('#title').text('Foods');
          //Adding each meal composition to the DOM
          meal.foodList().forEach( element => {
            console.log('we are in the iteration');
            $('#foods').append(element);
          })
          //Once the foods are displayed, this attaches a listener for the remove button for each list item.
          removeFoodListener();
        })
      })
      //Attach listener for the new food link
      $('#new-food-link').on('click', (e) => {
        e.preventDefault();
        e.stopPropagation();
        console.log('just clicked to create a new food for meal.');
        $('#create-title').text("Create Foods");
        if ($('body').data('new-form') === undefined) {
          let id = $('#new-food-link')[0].attributes.data.value
          //id is the current meals id that gets passed into the template.
          let newFoodForm = HandlebarsTemplates['new_food_form']({
            mealId: id
          })
          //Adds to the DOM a new food form for the meal.
          $('#add-form').prepend(newFoodForm);
          $('body').data('new-form', newFoodForm);
          //adds a hide form link to form.
          $('#hide-form').prepend('<a id="hide-form-link" href="#">hide form</a>')
          $('#new-food-link').hide();
        } else {
          console.log('In the else statement');
          $('#add-form').prepend($('body').data('new-form'))
          //display none for the new food link, and saving theis display property in jQuery data cache
          $('#new-food-link').hide();
          $('#hide-form').prepend('<a id="hide-form-link" href="#">hide form</a>')
        }
        //Once the form displays, attach a hide listener for the hide form link now dispayed on DOM.
        $('#hide-form').on('click', function(e) {
          e.preventDefault();
          e.stopPropagation();
          //Remove form from DOM, but retains jQuery data associated
          $('#new-food-form').detach();
          $('#create-title').text("");
          //Callling on the jQuery data cache to restore new-food-link initial display.
          $('#new-food-link').show();
        })
        //attaching a listener on the new food form
        $('#new-food-form').on('submit', function(e) {
          e.preventDefault();
          e.stopPropagation();
          //Callling on the jQuery data cache to restore new-food-link initial display.
          $('#new-food-link').show();
          let mealId = $('#new-food-form')[0].attributes.data.value;
          //creates a text string in standard URL-encoded notation
          let values = $(this).serialize();

          $.ajax({
            type: "POST",
            url: "/meals/" + mealId + '/foods',
            data: values,
            success: success,
            dataType: 'json'
          });

          function success(data) {
            //When POST req is successful, create a food object and mealComposition object from json response data.
            let food = new Food(data.food.id, data.food.name);
            let mealComposition = new MealComposition(data.meal_composition.id,
            data.meal_composition.food_id, data.meal_composition.food_servings, data.meal_composition.meal_id)
            //checking to see if the foods list is displayed. When foods list is displayed meal-foods will have a value other than undefined attached to body.
            if ($('body').data('meal-foods') === undefined) {
              //Dont show on DOM
              alert('You just created a food for this meal')
            } else {
              //the add food to list function takes a meal composition object as an argument, and adds it the end of the list of foods
              $('#foods').append(food.addFoodToList(mealComposition));
              const $arrList = $('#foods li button')
              //Grabs the last remove button and attach a listener to this button.
              $arrList.last().on('click', function(e) {
                e.preventDefault();
                e.stopPropagation();
                console.log('In the remove food function', this);

                let mealCompositionId = this.attributes.data.value;
                let mealId = $('body').data('meal-foods').id
                $(this).closest('ul').closest('li').remove();

                $.ajax({
                  type: "PATCH",
                  url: "/meals/" + mealId,
                  data: { meal: { remove_food: mealCompositionId } },
                  success: success,
                  dataType: 'json'
                });

                function success(data) {
                  console.log('We have data back from updating removing the food', data);
                  //take the data and create a new table
                  const macronutrientTable = new MacronutrientTable(data.table_data.carbohydrate, data.table_data.percent_calories_of_carbohydrate,
                  data.table_data.protein,data.table_data.percent_calories_of_protein, data.table_data.fat, data.table_data.percent_calories_of_fat)
                  //update the table on the DOM
                  macronutrientTable.updateTable();
                }
              })
            }
            const macronutrientTable = new MacronutrientTable(data.table_data.carbohydrate, data.table_data.percent_calories_of_carbohydrate,
            data.table_data.protein,data.table_data.percent_calories_of_protein, data.table_data.fat, data.table_data.percent_calories_of_fat)

            macronutrientTable.updateTable();
            $('#new-food-form').remove();
            $('#create-title').text("");
          }
        })
      })
      //attach a listener to the add food form.
      $('#add-food-form').submit(function(e) {
        e.preventDefault();
        e.stopPropagation();

        console.log('I submitted the add food form', this);
        //creates a text string in standard URL-encoded notation(query string)
        let values = $(this).serialize();
        let mealId = $(this)[0].attributes.data.value;
        $.ajax({
          type: "PATCH",
          url: "/meals/" + mealId,
          data: values,
          success: success,
          dataType: 'json'
        });

        function success(data) {

          console.log('the add food form was successful', data);

          let food = new Food(data.food.id, data.food.name);
          let mealComposition = new MealComposition(data.meal_composition.id,
          data.meal_composition.food_id, data.meal_composition.food_servings, data.meal_composition.meal_id)

          if ($('body').data('meal-foods') === undefined) {
            alert('You just added a food for this meal')
          } else {
            //the add food to list function takes a meal composition object as an argument
            $('#foods').append(food.addFoodToList(mealComposition));
            const $arrList = $('#foods li button')
            $arrList.last().on('click', function(e) {
              e.preventDefault();
              e.stopPropagation();
              console.log('In the remove food function', this);

              let mealCompositionId = this.attributes.data.value;
              let mealId = $('body').data('meal-foods').id
              $(this).closest('ul').closest('li').remove();

              $.ajax({
                type: "PATCH",
                url: "/meals/" + mealId,
                data: { meal: { remove_food: mealCompositionId } },
                success: success,
                dataType: 'json'
              });

              function success(data) {
                console.log('We have data back from updating removing the food', data);
                //take the data and create a new table
                macronutrientTable = new MacronutrientTable(data.table_data.carbohydrate, data.table_data.percent_calories_of_carbohydrate,
                data.table_data.protein,data.table_data.percent_calories_of_protein, data.table_data.fat, data.table_data.percent_calories_of_fat)
                //update the table on the DOM
                macronutrientTable.updateTable();
              }
            })
          }
          macronutrientTable = new MacronutrientTable(data.table_data.carbohydrate, data.table_data.percent_calories_of_carbohydrate,
          data.table_data.protein,data.table_data.percent_calories_of_protein, data.table_data.fat, data.table_data.percent_calories_of_fat)

          macronutrientTable.updateTable();
          //reset form
          $('#add-food-form').trigger('reset');
          //re-enable button
          resetSubmit();
        }
      })
    });

  </script>