config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :users, only: [:new, :show, :create, :edit, :update]

  resources :meals do
    resources :foods, only: [:new, :index, :create]
  end

  resources :foods, only: [:new, :show, :edit, :update, :destroy, :index]

  resources :sessions, only: [:new, :create, :destroy] do
    collection do
      get 'welcome'
    end
  end

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/food.rb
class Food < ApplicationRecord
  has_many :meal_compositions
  has_many :meals, through: :meal_compositions
  has_many :food_compositions
  has_many :macronutrients, through: :food_compositions

  validates :name, presence: true
  validates :name, uniqueness: true

  def calories_from_macronutrient(macronutrient)
    FoodComposition.total_calories_from_macro(self, macronutrient)
  end

  def percent_calories_macronutrient(macronutrient)
    (calories_from_macronutrient(macronutrient).to_f / calories * 100).round(2)
  end

  def grams_of_macronutrient(macronutrient)
    FoodComposition.total_grams_of_macronutrients_in_food(self, macronutrient)
  end

  def calories
    FoodComposition.total_calories(self)
  end

  def servings(meal)
    MealComposition.find_servings_of_food_in_meal(meal, self)
  end

  def macronutrients_grams=(macronutrients_grams)
    macronutrients_grams.each do |macronutrient_grams|
      food_composition = FoodComposition.find_by(food_id: self.id, macronutrient_id: macronutrient_grams[:id])
      macronutrient_grams[:grams] = 0 unless macronutrient_grams[:grams].present?
      if food_composition.nil? && macronutrient_grams[:id].present?
        self.food_compositions.build(macronutrient_id: macronutrient_grams[:id], macronutrient_grams: macronutrient_grams[:grams])
      else
        food_composition.update(macronutrient_grams: macronutrient_grams[:grams], macronutrient_id: macronutrient_grams[:id]) if macronutrient_grams[:id].present?
      end
    end
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authorized?
  before_action :find_meal, only: [:new]
  before_action :find_macronutrients, only: [:new, :create, :edit, :update]
  before_action :find_food, only: [:show, :edit, :update, :destroy]

  def index
    @foods = Food.all
    render json: @foods
  end

  def new
    @food = Food.new
  end

  def create
    @meal = Meal.find(params[:meal_id])
    @food = Food.new(food_params)
    associate_to_meal(@meal, @food, params[:food_servings])

    if @food.save
      respond_to do |format|
        format.html { redirect_to meal_path(@meal) }
        format.json { render json: {
          food: @food,
          meal_composition: @food.meal_compositions.last,
          table_data: NewTableDataService.new.call_meal(@meal)
           }
         }
      end
    else
      render :new
    end
  end

  def show
    find_meal if params[:meal_id]
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @food, status: 200 }
    end
  end

  def edit

  end

  def update
    if @food.update(food_params)

      redirect_to food_path(@food)
    else
      render :edit
    end
  end

  def destroy
    @food.food_compositions.each do |f|
      f.destroy
    end
    @food.meal_compositions.each do |m|
      m.destroy
    end
    @food.destroy
    redirect_to user_path(current_user), notice: "You just deleted #{@food.name} from database."
  end

  private

  def food_params
    params.require(:food).permit(:name, macronutrients_grams: [:id, :grams])
  end

  def associate_to_meal(meal, food, params_servings)
    params_servings = 1 unless params_servings.present?
    food.meal_compositions.build(meal_id: meal.id, food_servings: params_servings)
  end

  def find_meal
    @meal = Meal.find(params[:meal_id])
  end

  def find_macronutrients
    @macronutrients = Macronutrient.all
  end

  def find_food
    @food = Food.find(params[:id])
  end

end

app/helpers/foods_helper.rb
module FoodsHelper

  def food_errors_present?(food)
    if food.errors[:food_compositions].present?
      content_tag :p, class: "field_with_errors" do
        yield
      end
    else
      content_tag :p do
        yield
      end
    end
  end

  def food_grams?(food, macronutrient)
    if food.grams_of_macronutrient(macronutrient) == 0
      0
    else
      food.grams_of_macronutrient(macronutrient)
    end
  end

end

app/views/foods/_food_macronutrients.html.erb
<% macronutrients.each do |macronutrient| %>

  <%= food_errors_present?(food) do %>
    <%= label_tag macronutrient.category %>
      <br>
      <%= label_tag "Grams:" %>
      <%= hidden_field_tag "food[macronutrients_grams][][id]", macronutrient.id %>
      <%= text_field_tag "food[macronutrients_grams][][grams]", food_grams?(food, macronutrient) %>
  <% end %>
<% end %>

app/views/foods/edit.html.erb
<%= content_tag :h1, "Edit #{@food.name}" %>

<%= errors_list(@food) %>

<h3> Change Composition </h3>

<%= form_for(@food, url: food_path(@food), method: :patch) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= render 'food_macronutrients', macronutrients: @macronutrients, food: @food %>

  <%= f.submit %>
<% end %>

<%= content_tag :p do %>
  <%= button_to "Delete Food", food_path(@food), method: :delete, form_class: "delete-food", data: {confirm: "Are you sure you want to delete this food?"} %>
<% end %>

app/views/foods/index.html.erb
<%= content_tag :h1, "Foods for meal on #{meal_time(@meal)}" %>

<!-- a nested view -->
<% @meal.foods.each do |food| %>
  <div>
    <ul>
      <li>
        <%= food.name %>
        <ul>
          <li>
            <%= link_to "#{food.calories} calories", food_path(food) %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
<% end %>

app/views/foods/new.html.erb
<h1> Create A New Food </h1>

<%= errors_list(@food) %>

<%= form_for(@food, url: meal_foods_path(@meal)) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= render 'food_macronutrients', macronutrients: @macronutrients, food: @food %>

  <%= text_field_tag 'food_servings', nil, placeholder: 'servings' %>
  <%= f.submit %>
<% end %>

app/views/foods/show.html.erb
<!--should this view be nested?? -->
<%= content_tag :h1, @food.name %>

<%= content_tag :h3, "Total Calories: #{@food.calories}" %>

<h5> Macronutrient Tracker </h5>

<table class="pure-table">
    <thead>
        <tr>
            <th>Category</th>
            <th>Grams</th>
            <th>Percentage of Calories</th>
        </tr>
    </thead>
    <tbody>
      <%= render '/meals/macronutrients_table', macronutrients: @food.macronutrients, item: @food %>
    </tbody>
</table>

<%= content_tag :footer do %>
  <%= link_to "Update Food", edit_food_path(@food) %>

  <%= link_to "Back to Meal", meal_path(@meal) unless @meal.nil? %>
<% end %>